const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const { CollectionStore } = require('../backend/collections.cjs');
const { SettingsStore } = require('../backend/settings.cjs');
const fixture = require('./auth-fixture.cjs').createFixture({ now: () => Date.parse('2026-10-06T00:00:00Z') });
(async () => {
  let browser;
  try {
    const origin = await fixture.initialize(), auth = fixture.app.store;
    const credentials = { account: 'settings-member', password: 'Settings-password-2026' };
    const member = await auth.createUser({ ...credentials, display_name: '<img src=x onerror=window.settingsXss=1>' });
    for (let i = 0; i < 11; i++) await auth.createUser({ account: `setting-${i}`, password: 'Settings-password-2026', display_name: `测试成员 ${i}` });
    const actor = auth.db.prepare("SELECT * FROM users WHERE role='admin'").get();
    const instrument = new CollectionStore(auth, 'instruments').save({ code: 'SETTINGS-CAL', name: '设置校准验收', kind: 'other', status: 'fault', calibration_on: '2026-10-10' }, actor);
    browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE ? { executablePath: process.env.CHROME_EXECUTABLE } : {}) });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' }); await context.addInitScript(() => { Date.now = () => Date.parse('2026-10-06T00:00:00Z'); }); await fixture.signIn(context);
    const page = await context.newPage(), errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.goto(origin); await page.waitForFunction(() => document.querySelector('.profile-copy small').textContent === '管理员');
    const open = async view => {
      await page.locator('[data-page="settings"]').click();
      if (await page.locator('#settings-back').isVisible()) await page.locator('#settings-back').click();
      await page.locator(`[data-settings-view="${view}"]`).click();
      const heading = await page.locator('#settings-title').evaluate(element => ({ focused: element === document.activeElement, outline: getComputedStyle(element).outlineStyle }));
      assert.equal(heading.focused, true, 'Subpage heading remains announced after navigation');
      assert.equal(heading.outline, 'none', 'Static heading must not show a blue control border');
      const back = await page.locator('#settings-back').evaluate(element => {
        const style = getComputedStyle(element), rect = element.getBoundingClientRect();
        return { height: rect.height, width: rect.width, border: style.borderTopStyle, background: style.backgroundColor };
      });
      assert.ok(back.height >= 44 && back.width >= 150, 'Back action has a clear desktop hit area');
      assert.equal(back.border, 'solid', 'Back action has a visible button boundary');
      assert.notEqual(back.background, 'rgba(0, 0, 0, 0)');
    };
    const readyMembers = () => page.waitForFunction(() => document.querySelectorAll('#members-body tr').length > 0 && document.querySelector('#members-body').getAttribute('aria-busy') === 'false');
    const readyRules = () => page.waitForFunction(() => !document.querySelector('#reminders-save').disabled);
    const row = () => page.locator(`[data-member-id="${member.id}"]`);
    for (const width of [1280, 1440, 1920]) {
      await page.setViewportSize({ width, height: 1000 });
      await open('members'); await readyMembers();
      await page.keyboard.press('Shift+Tab');
      assert.equal(await page.locator('#settings-back').evaluate(element => element === document.activeElement), true);
      assert.equal(await page.locator('#settings-back').evaluate(element => getComputedStyle(element).outlineStyle), 'solid', 'Keyboard users retain a visible button focus');
      await page.keyboard.press('Enter');
      assert.equal(await page.locator('#settings-home').isVisible(), true);
      assert.equal(await page.locator('[data-settings-view="members"]').evaluate(element => element === document.activeElement), true);
      await page.locator('[data-settings-view="members"]').click(); await readyMembers();
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      assert.equal(await page.locator('#members-body tr').count(), 12);
      assert.ok(await page.locator('.member-actions').evaluateAll(groups => groups.every(group => {
        const [first, second] = [...group.children].map(button => button.getBoundingClientRect());
        return first.right <= second.left || first.bottom <= second.top;
      })), 'Member operation controls must not overlap');
      assert.match(await page.locator('#members-summary').innerText(), /13 位成员 · 1 位有效管理员/);
      if (width === 1440) await page.screenshot({ path: '/tmp/lab-settings-members.png', fullPage: true });
      await page.locator('#members-next').click(); await page.waitForFunction(() => document.querySelector('#members-page-info').textContent.includes('第 2'));
      assert.equal(await page.locator('#members-body tr').count(), 1);
      await open('reminders'); await readyRules();
      assert.equal(await page.locator('[name="expiry_days"]').inputValue(), '60');
      if (width === 1440) await page.screenshot({ path: '/tmp/lab-settings-reminders.png', fullPage: true });
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await open('help'); if (await page.locator('#settings-help details').first().getAttribute('open') === null) await page.locator('#settings-help summary').first().click();
      assert.ok(await page.locator('#settings-help details').first().getAttribute('open') !== null);
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      if (width === 1440) await page.screenshot({ path: '/tmp/lab-settings-help.png', fullPage: true });
    }
    await open('members'); await readyMembers();
    await page.locator('#members-filter [name="q"]').fill('settings-member'); await page.locator('#members-filter [type="submit"]').click(); await readyMembers();
    assert.equal(await page.locator('#members-body tr').count(), 1); assert.match(await row().innerText(), /<img src=x/);
    assert.equal(await page.evaluate(() => window.settingsXss), undefined);
    await page.locator('#members-filter [name="role"]').selectOption('admin'); await page.locator('#members-filter [type="submit"]').click();
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('暂无匹配'));
    await page.locator('#members-filter [name="role"]').selectOption(''); await page.locator('#members-filter [type="submit"]').click(); await readyMembers();
    // Cancel leaves both the database and UI unchanged.
    let confirmation = page.waitForEvent('dialog').then(async dialog => { assert.equal(dialog.type(), 'confirm'); assert.match(dialog.message(), /settings-member/); await dialog.dismiss(); });
    await row().getByRole('button', { name: '设为管理员', exact: true }).click(); await confirmation;
    assert.equal(auth.db.prepare('SELECT role FROM users WHERE id=?').get(member.id).role, 'member');
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept());
    await row().getByRole('button', { name: '设为管理员', exact: true }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('已保存'));
    assert.match(await row().innerText(), /管理员/);
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await row().getByRole('button', { name: '停用账号' }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-body').textContent.includes('恢复账号'));
    await page.locator('#members-filter [name="active"]').selectOption('0'); await page.locator('#members-filter [type="submit"]').click(); await readyMembers(); assert.equal(await page.locator('#members-body tr').count(), 1);
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await row().getByRole('button', { name: '恢复账号' }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('已保存')); assert.equal(await page.locator('#members-body tr').count(), 0);
    await page.locator('#members-filter [name="active"]').selectOption(''); await page.locator('#members-filter [type="submit"]').click(); await readyMembers();
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await row().getByRole('button', { name: '设为普通成员' }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('已保存'));
    // Server-side change makes the visible member version stale.
    auth.setActive(credentials.account, false);
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await row().getByRole('button', { name: '设为管理员', exact: true }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('重新加载'));
    await page.locator('#members-retry').click(); await readyMembers();
    auth.setActive(credentials.account, true);
    await page.route('**/api/v1/settings/members?*', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '成员失败测试' } }) }));
    await page.locator('#members-filter [type="submit"]').click(); await page.locator('#members-retry').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#members-body tr').count(), 0);
    await page.unroute('**/api/v1/settings/members?*'); await page.locator('#members-retry').click(); await readyMembers();
    await open('reminders'); await readyRules();
    await page.locator('[name="expiry_days"]').fill('7'); await page.locator('[name="calibration_days"]').fill('3');
    let releaseSave;
    const saveGate = new Promise(resolve => { releaseSave = resolve; });
    let writes = 0;
    await page.route('**/api/v1/settings/reminders', async route => {
      if (route.request().method() === 'PATCH') { writes++; await saveGate; }
      await route.continue();
    });
    await page.locator('#reminders-save').click();
    assert.equal(await page.locator('#reminders-save').isDisabled(), true);
    assert.equal(await page.locator('#reminders-reload').isDisabled(), true);
    await page.evaluate(() => { window.dispatchEvent(new CustomEvent('lab-session', { detail: settingsUser })); loadReminderSettings(); });
    assert.equal(await page.locator('[name="expiry_days"]').isDisabled(), true);
    releaseSave(); await page.waitForFunction(() => document.querySelector('#reminders-message').textContent.includes('已保存'));
    assert.equal(writes, 1); await page.unroute('**/api/v1/settings/reminders');
    assert.equal(await page.locator('#metric-expiry-hint').textContent(), '未来 7 天内到期');
    assert.equal(auth.db.prepare('SELECT calibration_days FROM reminder_settings').get().calibration_days, 3);
    await page.locator('#reminders-reload').click(); await readyRules(); assert.equal(await page.locator('[name="expiry_days"]').inputValue(), '7');
    const settings = new SettingsStore(auth), rules = settings.reminders();
    const token = (await context.cookies()).find(cookie => cookie.name === 'lab_session').value;
    const { updated_at, max_days, ...payload } = rules; settings.updateReminders({ ...payload, calibration_days: 5 }, token);
    await page.locator('#reminders-save').click(); await page.waitForFunction(() => document.querySelector('#reminders-message').textContent.includes('重新加载'));
    assert.equal(await page.locator('#reminders-save').isDisabled(), true);
    await page.locator('#reminders-retry').click(); await readyRules(); assert.equal(await page.locator('[name="calibration_days"]').inputValue(), '5');
    await page.locator('[name="expiry_days"]').fill('366'); await page.locator('#reminders-save').click();
    assert.equal(await page.locator('[name="expiry_days"]').evaluate(input => input.validity.rangeOverflow), true);
    await page.locator('[name="expiry_days"]').fill('7');
    await page.locator('[data-page="overview"]').click(); await page.waitForFunction(() => document.querySelector('[data-filter="calibration"] span').textContent === '1');
    await page.locator('[data-filter="calibration"]').click(); await page.waitForFunction(() => document.querySelector('#inventory-body').textContent.includes('设置校准验收'));
    await page.locator('#inventory-body button').click(); await page.waitForFunction(() => document.querySelector('#collection-detail-dialog').open && document.querySelector('#collection-detail').textContent.includes('SETTINGS-CAL'));
    assert.match(await page.locator('#collection-detail-dialog').innerText(), /SETTINGS-CAL/);
    await page.locator('#collection-detail-dialog [aria-label="关闭详情"]').click();
    assert.equal(auth.db.prepare('SELECT status FROM instruments WHERE id=?').get(instrument.id).status, 'fault');
    await open('reminders'); await readyRules(); await page.locator('[name="calibration_enabled"]').uncheck(); await page.locator('#reminders-save').click();
    await page.waitForFunction(() => document.querySelector('#reminders-message').textContent.includes('已保存')); assert.equal(await page.locator('[data-filter="calibration"] span').textContent(), '0');
    await page.route('**/api/v1/settings/reminders', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '规则失败测试' } }) }));
    await page.locator('#reminders-reload').click(); await page.locator('#reminders-retry').waitFor({ state: 'visible' }); assert.equal(await page.locator('#reminders-save').isDisabled(), true);
    await page.unroute('**/api/v1/settings/reminders'); await page.locator('#reminders-retry').click(); await readyRules();
    const readerContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    await readerContext.request.post(origin + '/api/v1/auth/login', { headers: { Origin: origin }, data: credentials });
    await readerContext.addInitScript(() => { Date.now = () => Date.parse('2026-10-06T00:00:00Z'); });
    const reader = await readerContext.newPage(); await reader.goto(origin); await reader.waitForFunction(() => document.querySelector('.profile-copy small').textContent === '普通成员');
    await reader.locator('[data-page="settings"]').click(); await reader.locator('[data-settings-view="reminders"]').click();
    await reader.waitForFunction(() => !document.querySelector('#reminders-save').disabled);
    assert.equal(await reader.locator('[name="expiry_days"]').isDisabled(), true);
    const denied = reader.waitForEvent('dialog').then(async dialog => { assert.equal(dialog.message(), '您没有该权限'); await dialog.accept(); }); await reader.locator('#reminders-save').click(); await denied;
    // Self demotion redirects to login while leaving another valid administrator.
    await open('members'); await page.locator('#members-filter [name="q"]').fill(''); await page.locator('#members-filter [type="submit"]').click(); await readyMembers();
    const selfRow = page.locator(`[data-member-id="${actor.id}"]`);
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await selfRow.getByRole('button', { name: '设为普通成员' }).click(); await confirmation;
    await page.waitForFunction(() => document.querySelector('#members-message').textContent.includes('最后一位'));
    auth.db.prepare("UPDATE users SET role='admin' WHERE id=?").run(member.id);
    await page.locator('#members-filter [type="submit"]').click(); await readyMembers();
    confirmation = page.waitForEvent('dialog').then(dialog => dialog.accept()); await selfRow.getByRole('button', { name: '设为普通成员' }).click(); await confirmation; await page.waitForURL('**/login.html');
    assert.deepEqual(errors, []); await readerContext.close(); await context.close();
    console.log('Settings browser validation passed: three desktop widths, entries/back/help, real members/pagination/search/filters, confirmations/cancel, role/status changes, self-session revocation, last-admin protection, conflict/retry, rules/workbench/calibration detail and read-only protection.');
  } finally { if (browser) await browser.close(); await fixture.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
