const assert = require('node:assert/strict');
const { chromium } = require('playwright');
const fixture = require('./auth-fixture.cjs').createFixture();
(async () => {
  const origin = await fixture.initialize();
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_EXECUTABLE ? { executablePath: process.env.CHROME_EXECUTABLE } : {}) });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
    const page = await context.newPage();
    const errors = [], submissions = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (request.url().endsWith('/auth/register')) submissions.push(request); });
    await page.goto(`${origin}/login.html`);
    await page.locator('#show-register').click();
    assert.equal(await page.locator('#register-form').isVisible(), true);
    assert.equal(await page.locator('#login-form').isVisible(), false);
    assert.equal(await page.locator('#register-name').evaluate(field => field === document.activeElement), true);
    for (const [width, height] of [[1280, 720], [1280, 800], [1440, 900], [1920, 1080]]) {
      await page.setViewportSize({ width, height });
      assert.equal(await page.locator('.login-content').evaluate(element => { const rect = element.getBoundingClientRect(); return rect.top >= 0 && rect.bottom <= innerHeight; }), true, `Registration fits ${width}×${height}`);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    }
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.screenshot({ path: '/tmp/lab-registration.png', fullPage: true });
    await page.locator('#register-button').click();
    assert.equal(await page.locator('#register-form [aria-invalid="true"]').count(), 4);
    assert.equal(await page.locator('#register-name').evaluate(field => field === document.activeElement), true);
    await page.locator('#register-name').fill('注册成员');
    await page.locator('#register-account').fill('不合法账号');
    await page.locator('#register-password').fill('Pass123!');
    await page.locator('#register-confirm').fill('Pass123!');
    await page.locator('#register-button').click();
    assert.match(await page.locator('#register-account-error').textContent(), /3–80/);
    assert.match(await page.locator('#register-password-error').textContent(), /9–128/);
    await page.locator('#register-account').fill(fixture.credentials.account);
    await page.locator('#register-password').fill('Newpass9!');
    await page.locator('#register-confirm').fill('Otherpass!');
    await page.locator('#register-confirm').press('Enter');
    assert.match(await page.locator('#register-confirm-error').textContent(), /不一致/);
    assert.equal(submissions.length, 0, 'Client validation blocks invalid submissions');
    await page.locator('#toggle-register-password').click();
    assert.equal(await page.locator('#register-password').getAttribute('type'), 'text');
    await page.locator('#toggle-register-password').click();
    await page.locator('#register-confirm').fill('Newpass9!');
    await page.route('**/api/v1/auth/register', route => route.abort('failed'));
    await page.locator('#register-button').click();
    await page.locator('#register-button[data-state="error"]').waitFor();
    assert.match(await page.locator('#register-message').textContent(), /无法连接/);
    assert.equal(await page.locator('#register-name').inputValue(), '注册成员');
    await page.unroute('**/api/v1/auth/register');
    await page.locator('#register-button').click();
    await page.waitForFunction(() => document.querySelector('#register-message').textContent.includes('账号已存在'));
    assert.equal(await page.locator('#register-account').getAttribute('aria-invalid'), 'true');
    await page.locator('#register-account').fill('browser_member');
    let release;
    const pause = new Promise(resolve => { release = resolve; });
    await page.route('**/api/v1/auth/register', async route => { await pause; await route.continue(); });
    await page.locator('#register-confirm').press('Enter');
    assert.equal(await page.locator('#register-button').isDisabled(), true);
    assert.equal(await page.locator('#show-login').isDisabled(), true);
    assert.equal(await page.locator('#register-account').isDisabled(), true);
    release();
    await page.locator('#login-form').waitFor({ state: 'visible' });
    assert.equal(await page.locator('#account').inputValue(), 'browser_member');
    assert.match(await page.locator('#login-message').textContent(), /注册成功/);
    assert.equal(await page.locator('#register-password').inputValue(), '');
    await page.locator('#password').fill('Newpass9!');
    await page.locator('#password').press('Enter'); await page.waitForURL('**/index.html');
    await page.waitForFunction(() => document.querySelector('.profile-copy strong').textContent === '注册成员');
    assert.equal(await page.locator('.profile-copy small').textContent(), '普通成员');
    await page.locator('.profile-button').click(); await page.locator('#logout-button').click(); await page.waitForURL('**/login.html');
    await page.locator('#show-register').click();
    await page.locator('#register-password').fill('Newpass9!');
    await page.locator('#show-login').click();
    assert.equal(await page.locator('#register-password').inputValue(), '');
    assert.equal(await page.locator('#login-form').isVisible(), true);
    assert.deepEqual(errors, []);
    console.log('Registration browser validation passed: four desktop sizes, switching, validation, duplicate account, network failure, loading lock, member registration and real login.');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => fixture.close());
